{{- $fullName := include "bitwarden.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bitwarden.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bitwarden.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        command:
        {{- range $val := .Values.deployment.command }}
        - {{ $val | quote }}
        {{- end}}
        envFrom:
        - configMapRef:
            name: {{ $fullName }}-conf
        {{- if .Values.secrets.name }}
        - secretRef:
            name: {{ .Values.secrets.name }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.bitwarden.rocket_port }}
          protocol: TCP
        {{- if .Values.bitwarden.websocket_enabled }}
        - name: websocket
          containerPort: {{ .Values.bitwarden.websocket_port }}
          protocol: TCP
        {{- end }}
        {{- if .Values.deployment.healthCheck.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        {{- end }}
        {{ if .Values.storage.enabled -}}
        volumeMounts:
        - mountPath: {{ .Values.storage.path }}
          name: data-storage
        {{ end }}
      {{- with .Values.deployment.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ if .Values.storage.enabled -}}
      volumes:
      - name: data-storage
        persistentVolumeClaim:
         claimName: {{ $fullName }}-pv
      {{ end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.deployment.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
