{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bitwarden.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if .Values.bitwarden.websocket_enabled }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    {{- end }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        - backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ .Values.service.port }}
          path: '/'
          pathType: ImplementationSpecific
        {{- if .Values.bitwarden.websocket_enabled }}
        - backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ .Values.bitwarden.websocket_port }}
          path: '/notifications/hub'
          pathType: ImplementationSpecific
        - backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ .Values.service.port }}
          path: '/notifications/hub/negotiate'
          pathType: ImplementationSpecific
        {{- end }}
{{- end }}
